name: farmer_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  carousel_slider: ^4.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  email_validator: ^2.1.17
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.6
  get: ^4.6.5
  firebase_storage: ^11.0.10
  lottie: ^1.1.0
  smart_auth: ^1.0.7
  dotted_border: ^2.0.0+3
  toggle_switch: ^2.0.1
  intl_phone_field: ^3.1.0
  badges: ^2.0.3
  pinput: ^2.2.20
  dropdown_search: ^5.0.5
  url_launcher: ^6.1.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  uuid: ^3.0.7
  local_auth: ^2.1.3
  animated_text_kit: ^4.2.2
  modal_progress_hud: ^0.1.3
  edge_alert: ^0.0.1
  google_sign_in: ^5.4.3
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.4.0
  flutter_launcher_icons: ^0.11.0
  animated_splash_screen: ^1.3.0
  flutterfire_ui: ^0.4.3+20
  provider: ^6.0.5
  age_calculator: ^1.0.0
  google_fonts: ^4.0.3
  razorpay_flutter: ^1.3.4
  image_cropper: ^3.0.1







flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_forground: "assets/images/logo1.png"

  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Itim
      fonts:
        - asset: assets\images\fonts\Itim-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets\images\fonts\Oswald-VariableFont_wght.ttf

    - family: RobotoCondensed
      fonts:
        - asset: assets\images\fonts\RobotoCondensed-Bold.ttf
        - asset: assets\images\fonts\RobotoCondensed-Italic.ttf

    - family: pacifico
      fonts:
        - asset: assets\images\fonts\Pacifico-Regular.ttf

      

  assets:
    - assets/images/bear.png
    - assets/images/farming.png
    - assets/images/pump.png
    - assets/images/workshop.png
    - assets/images/cultivators.png
    - assets/images/fogging.png
    - assets/images/harvester.png
    - assets/images/manual.png
    - assets/images/sprayers.png
    - assets/images/bigmachine.png
    - assets/images/Thumb.png
    - assets/images/compressor.png
    - assets/images/welding.png
    - assets/images/green.png
    - assets/images/red.png    
    - assets/images/autom.png
    - assets/images/delete.png
    - assets/images/remove.png    
    - assets/images/mathan.png
    - assets/images/outdoor.jpg
    - assets/images/farming.jpg
    - assets/images/workshop.jpg
    - assets/images/handshake.png    
    - assets/images/bigwork.png    
    - assets/images/outpower.png    
    - assets/images/landscaping.png    
    - assets/images/construction.png    
    - assets/images/solar.png    
    - assets/images/cleaning.png    
    - assets/images/outdoor.jpeg    
    - assets/images/workshop.jpeg    
    - assets/images/farming.jpeg
    - assets/images/page.png
    - assets/images/sanika.jpeg
    - assets/images/sanika1.png
    - assets/images/cart.png
    - assets/images/farm.png
    - assets/images/user.png
    - assets/images/camera.png
    - assets/images/front.png
    - assets/images/back.png
    - assets/images/left.png
    - assets/images/right.png
    - assets/images/logo.png
    - assets/images/t&c.png
    - assets/images/logout.png
    - assets/images/address.png
    - assets/images/products.png
    - assets/images/help.png
    - assets/images/order.png
    - assets/images/setting.png
    - assets/images/outdoor.png
    - assets/images/workshop2.png
    - assets/images/GOTOOL.gif
    - assets/images/alert.png
    - assets/images/gallary.jpg
    - assets/images/gallary.png
    - assets/images/front1.png
    - assets/images/back1.png
    - assets/images/left1.png
    - assets/images/right1.png
    - assets/images/shield_tick.png
    - assets/images/address1.png
    - assets/images/signup.png
    - assets/images/TP1.jpg
    - assets/images/information.png
    - assets/images/pg1.png
    - assets/images/Go.gif
    

    
    
       
       

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
